#!/usr/bin/env php
<?php

require_once __DIR__ . '/../vendor/autoload.php';

use Symfony\Component\Console\Application;
use Claroline\Command\PackageGeneratorCommand;

$application = new Application();
$application->add(new PackageGeneratorCommand());
$application->run();
